---
- name: "Install OS Dependencies"
  ansible.builtin.apt:
    name: "{{ wsl_config_os_dependencies }}"
    state: present
  tags: wsl-win-integration

- name: "PIP Dependencies"
  ansible.builtin.pip:
    name: "{{ wsl_config_pip_dependencies }}"
    state: present
    executable: pip3
  tags: wsl-win-integration

- name: "Set user cache directory"
  ansible.builtin.file:
    dest: "/var/cache/{{ item.username }}"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: "0744"
  loop: "{{ wsl_config_users }}"
  tags: wsl-win-integration

- name: "Fix WSL2 Windows Binary Interop"
  ansible.builtin.include_tasks: bin-interop.yml
  tags: wsl-win-integration

- name: "Fix WSL2 Systemd User Session"
  ansible.builtin.include_tasks: systemd-user-session.yml
  tags: wsl-win-integration

- name: "Fix WSL2 Windows Networking"
  ansible.builtin.include_tasks: network-fixes.yml
  when: wsl_version == "wsl2"
  tags: wsl-win-integration

- name: "Host IP Address Advertiser"
  ansible.builtin.include_tasks: host-ip-advertiser.yml
  tags: wsl-win-integration

- name: "Disable Unwanted Services"
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
    masked: false
  loop: "{{ wsl_config_nostart_services }}"
  tags: wsl-win-integration
