#!/bin/bash

exec >> "/var/log/$(basename $0).log" 2>&1
echo "----------------------------------"
date

run_level="$1"

if [[ -z "${run_level}" ]] ; then
    echo "Need to specify a run level"
    exit 127
fi

if [[ ! -d "/etc/rc${run_level}.d/" ]] ; then
    echo "Need to specify a run level"
    exit 127
fi

echo "Entering WSL runlevel ${run_level}"

for rc_service in /etc/rc${run_level}.d/K*; do
    echo ">>> START - Running \"${rc_service} stop\""
    [[ -e "${rc_service}" ]] && "${rc_service}" stop
    echo ""
done

for rc_service in /etc/rc${run_level}.d/S*; do
    echo ">>> STOP - Running \"${rc_service} start\""
    [[ -e "${rc_service}" ]] && "${rc_service}" start
    echo ""
done

echo "WSL runlevel change done"
echo ""
